default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'wacca-no-theoretical-value_development' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'wacca-no-theoretical-value_development' %>

test:
  <<: *default
  database: wacca-no-theoretical-value_test

production:
  <<: *default
  database: wacca-no-theoretical-value_production
  url: <%= ENV['DATABASE_URL'] %>
